[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = [
    "../../drivers/ui/src",
    "../../interactions/src",
]

[serve]
# The address to serve on.
address = "0.0.0.0"
